### PR TITLE
Specify Yarn as the package manager in package.json

### PR DESCRIPTION
**Pull request by TixieSalander**
## Proposed changes

It have been automatically added by Yarn (runed in v1.22.22) when I've started the `watch-assets` task so, I think it should be added to the code base.

cf. https://yarnpkg.com/configuration/manifest#packageManager

## Contributor checklist

- [x] ~~My PR is related to \<insert ticket number>~~ (no issue)
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/flora-pm/flora-server/blob/development/CONTRIBUTING.md)
- [ ] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)
- [x] ~~I have updated documentation in `./docs/docs` if a public feature has a behaviour change~~ no behaviour change

### CODE REVIEW

**Comment by tchoutri** [comment]
Yeah I think it must be VSCode doing it, because I remember it happened last time we paired. Let's comply then. :)

**Review by tchoutri — APPROVED** [review]

**Comment by TixieSalander** [comment]
@tchoutri I don't think it's VSCode, I don't have it opened, remove the change, re-launch yarn and it have been added again

**Comment by tchoutri** [comment]
@TixieSalander Interesting! Which version of yarn do you use, by any chance?

**Comment by TixieSalander** [comment]
@tchoutri v1.22.22, runned inside Docker

**Pull request merged**
