### PR TITLE
[FLORA-142] Add components to dependencies page

### PR DESCRIPTION
**Pull request by RaoulHC**
## Proposed 

Expands the dependencies page to list the dependencies of each components, using the HTML details tag.

Opening is as draft for now: the package page might want to be changed to always have a link to the full components dependencies page; probably want the number of each components dependencies in the summary tag; and one of the tests needs updating. I'm relatively inexperienced with HTML and CSS, so do say if there are better approaches for this!

Attached two screenshots for what it looks like so far.

Screen Shot 2023-03-02 at 00 09 02
Screen Shot 2023-03-02 at 00 02 35

## Contributor checklist

- [x] My PR is related to #142 
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/flora-pm/flora-server/blob/development/CONTRIBUTING.md)
- [x] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)

### CODE REVIEW

**Comment by skykanin** [comment]
Personally I like this approach for listing component dependencies :+1:

**Comment by exaexa** [comment]
Just a random idea, can we also have the dependency version bounds listed?

(pro-level: nice compatibility matrix between all version of the dependee and the dependent?)

**Comment by tchoutri** [comment]
@RaoulHC Thank you for this PR. As you can see I am gathering more opinions than just my own. :) 
Especially the use of `details` might conflict with screen readers for accessibility, and while not a total blocker I'd like to know what we can do to improve it after this gets merged.

**Comment by RaoulHC** [comment]
@exaexa and @tomsmeding the version dependency bounds do get listed, I just happened to pick a poor example that doesn't actually have constraints, if you look at the current flora website you should see how constraints get listed (e.g. [here](https://flora.pm/packages/%40hackage/effectful/2.2.2.0/dependencies)). My change doesn't actually change how the dependencies are displayed, just does it for each component and makes it collapsible.

@tchoutri I'll have a bit more of a dig into it with regards to accessibility. When looking for how to do collapsible lists it definitely seemed like the cleanest approach, other approaches requiring some amount of js like [this](https://www.w3schools.com/howto/howto_js_collapsible.asp). Should get time to finish this off on Sunday.

**Comment by tchoutri** [comment]
@RaoulHC Yes, sometimes being more accessible requires JavaScript :) 

Here are some interesting reads on the subject of accessibility of `<details>`:

https://www.hassellinclusion.com/blog/accessible-accordions-part-2-using-details-summary/

**Comment by tchoutri** [comment]
@RaoulHC Another thing to think about is providing the shorted path to relevant information. Perhaps the main library component should be expanded by default (or not even behind a `<details>` tag). If there's only an executable and no library component, it could be the same.

**Comment by RaoulHC** [comment]
> @RaoulHC Yes, sometimes being more accessible requires JavaScript :)
>  [snip]

From a quick read of those it *seems* like `<details>` should be pretty well supported in the main browsers now, I hadn't realised it was actually a relatively new HTML feature.

Yeah having the library expanded by default had crossed my mind but I haven't looked into the details of it yet, but I do agree that that behaviour might be the nicest.

**Comment by RaoulHC** [comment]
@tchoutri This is good to review now.

I've gone for the details tag being open by default when there's only a single component. I think makes the most sense rather than try and figure out some heuristic for what a user might want, something that will often be wrong for more complicated packages.

I've also fixed the PR title check so I can get all the green ticks.

On a related topic would it make sense to also do dependents by component? It does get the dependents regardless of the component, but it might make sense to list which components use a library. I think it requires some changes to the database schema, so probably warrants an issue and a separate PR.

**Comment by tchoutri** [comment]
Jolly good! 

> On a related topic would it make sense to also do dependents by component? It does get the dependents regardless of the component, but it might make sense to list which components use a library. I think it requires some changes to the database schema, so probably warrants an issue and a separate PR.

Yeah create a ticket and I'll add it to https://github.com/orgs/flora-pm/projects/2 :)

**Review by tchoutri — APPROVED** [review]
Wonderful contribution, thanks a lot :)

**Pull request merged**
