### PR TITLE
[NO-ISSUE] Enable live reload of pages upon server restart

### PR DESCRIPTION
**Pull request by tchoutri**
## Proposed changes

This PR introduces a live reload websocket controlled by HTMX. 
This requires us to switch to `lucid2`, for which some libraries are not yet compatible.

## Opened tickets

* https://github.com/monadicsystems/lucid-alpine/issues/4
* https://github.com/ocharles/lucid-svg
* https://github.com/bigskysoftware/htmx-extensions/issues/92

## Contributor checklist

- [ ] My PR is related to \<insert ticket number> 
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/flora-pm/flora-server/blob/development/CONTRIBUTING.md)
- [x] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)
- [ ] I have updated documentation in `./docs/docs` if a public feature has a behaviour change

### CODE REVIEW

**Comment by tchoutri** [comment]
@TristanCacqueray I see in https://github.com/TristanCacqueray/haskell-xstatic/tree/main/demo-websockets-ki-htmx that you do not use the HTMX [websocket extension](https://github.com/bigskysoftware/htmx-extensions/blob/main/src/ws/README.md). Is it worth it to do that myself or should I delegate as much work as possible?

**Comment by TristanCacqueray** [comment]
@tchoutri this was done in a earlier version of htmx which provided the extension out of the box, I think the latest version requires you to install the extension.

**Comment by tchoutri** [comment]
Oh nice! I'll explore the SSE option

**Comment by tchoutri** [comment]
Thanks a lot @MangoIV!

**Pull request merged**
