### PR TITLE
Implement working search bar in reverse dependencies

### PR DESCRIPTION
**Pull request by dylan-thinnes**
## Proposed changes

Reverse dependency lists (a.k.a dependents) can get huge, e.g. for the lens library, which makes pagination impractical. This implements a search bar in the reverse dependencies page.

TODOS:
- [ ] There is definitely still some work to be done on styling the search bar to be a nicer size, but this is something I'd rather get feedback on.
- [ ] There's also some work to be done on cleaning up duplication in the SQL code, I'll make them once we're certain that the semantic behaviour as implemented now is what we want.

## Contributor checklist

- [X] My PR is related to https://github.com/flora-pm/flora-server/issues/388 
- [X] I have read and understood the [CONTRIBUTING guide](https://github.com/flora-pm/flora-server/blob/development/CONTRIBUTING.md)
- [x] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)

### CODE REVIEW

**Comment by tchoutri** [comment]
here it was it looks like right now:

Screenshot 2023-06-11 at 13-54-46 @haskell_base

**Comment by tchoutri** [comment]
@dylan-thinnes Hi! Would you like me to take the relay on this PR if you're having a hard time finishing it? I know it's hard to find the motivation and excitement after the hackathon has ended. :)

**Comment by dylan-thinnes** [comment]
Haha heya! No worries, I just was taking some time off to recover. I'll stage some of the work in the next few days and you can tell me if it feels like things are heading in the direction you think's good.

**Comment by tchoutri** [comment]
@dylan-thinnes if that's not asking too much, I'd like to know how you're doing with the PR and if you'd like to pair with me sometime, or you can just push your code and I'll take it from here. :)

**Comment by tchoutri** [comment]
@dylan-thinnes If you don't mind I will port your PR and adapt it to the latest changes that landed in `development`. :) Thanks a bunch for all the work!

**Comment by tchoutri** [comment]
Closed by #476

**Pull request closed without merging**
