### PR TITLE
[NO-ISSUE] Switch flake.nix to use horizon-platform at ghc 9.4.2

### PR DESCRIPTION
**Pull request by locallycompact**
Hi. I will be trying flora-server over at https://horizon-haskell.net/ to track abandoned source and so I'd like to maintain the flake if I may. I've lifted all of flora's dependencies into the build plan upstream and the flake now builds where it did not before.

### CODE REVIEW

**Comment by blackheaven** [comment]
It's a huge improvement, however, it uses soufflé 2.3 instead of 2.2

**Comment by tchoutri** [comment]
@locallycompact Hi, and thank you for this PR. :) The website of [horizon-haskell.net](https://horizon-haskell.net/) however says that it is for GHC 9.4.2 and beyond, which strikes me as odd since Flora is on GHC 9.2. Is this a soft lower bound?

**Comment by locallycompact** [comment]
@blackheaven Is this likely to cause issue?

@tchoutri Soft lower bound yes. The ports I've done moving packages from 9.2 -> 9.4 have mostly been inconsequential, except where the GHC API has been used directly, such as in type checker plugins. "Normal" libraries typically only need their bounds checked and everything is basically the same.

**Comment by blackheaven** [comment]
> @blackheaven Is this likely to cause issue?

I don't know, @tchoutri made this comment on my other PR

**Comment by tchoutri** [comment]
@locallycompact 

> @blackheaven Is this likely to cause issue?

Yes, headers change and the version of the Soufflé bindings library must be kept in sync with the version of Soufflé

> @tchoutri Soft lower bound yes. The ports I've done moving packages from 9.2 -> 9.4 have mostly been inconsequential, except where the GHC API has been used directly, such as in type checker plugins. "Normal" libraries typically only need their bounds checked and everything is basically the same.

Okay so this doesn't force me to switch to GHC 9.4. Great :)

**Review by tchoutri — APPROVED** [review]

**Pull request merged**
