### PR TITLE
[NO-ISSUE] Add nix flake CI

### PR DESCRIPTION
**Pull request by blackheaven**
It'll take to

- [x] Configure Github Actions' `CACHIX_AUTH_TOKEN`
- [x] Merge #252 first

### CODE REVIEW

**Comment by tchoutri** [comment]
@blackheaven You're going to need `environment: nix` in the job stanza :)

**Comment by blackheaven** [comment]
TIL, thanks

**Review by tchoutri — APPROVED** [review]

**Comment by tchoutri** [comment]
@mergify rebase

**Comment by tchoutri** [comment]
@mergifyIO rebase

**Comment by tchoutri** [comment]
@mergifyIO rebase

**Pull request closed without merging**
