### PR TITLE
[NO-ISSUE] Update to GHC 9.6

### PR DESCRIPTION
**Pull request by locallycompact**
## Contributor checklist

- [x] My PR is related to \<insert ticket number> 
- [x] I have read and understood the [CONTRIBUTING guide](https://github.com/flora-pm/flora-server/blob/development/CONTRIBUTING.md)
- [ ] I have inserted my change and a link to this PR in the [CHANGELOG](https://github.com/flora-pm/flora-server/blob/development/CHANGELOG.md)

### CODE REVIEW

**Comment by locallycompact** [comment]
The souffle-haskell bound was removed because of an issue with the 4.0.0 release

https://github.com/luc-tielen/souffle-haskell/issues/76

**Comment by tchoutri** [comment]
> /nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/strip: /nix/store/7v1wkcr318dxdf4f8b0mc1s425lhb3w4-ghc-lib-parser-9.6.3.20231014/lib/ghc-9.6.3/lib/x86_64-linux-ghc-9.6.3/ghc-lib-parser-9.6.3.20231014-Luate27CDwiCm5Bxd4RwnI/stdoaGzn: **No space left on device**

Incredible

**Comment by tchoutri** [comment]
> 2024-02-19T14:41:56.8844629Z flora> <no location info>: error:
2024-02-19T14:41:56.8846108Z flora>     /build/ghc2206_0/ghc_399.s: hClose: resource exhausted (No space left on device)
2024-02-19T14:41:56.8848959Z hls-alternate-number-format-plugin> dist/build/libHShls-alternate-number-format-plugin-2.4.0.0-7jKPYhzbG6b23LcyN7wyxA-ghc9.6.3.a: withBinaryFile: resource exhausted (No space left on device)
2024-02-19T14:41:56.8858264Z hls-cabal-fmt-plugin> /nix/store/fzlkaj1ax7gl655blfcr6zzvml1vx3bj-binutils-2.40/bin/ranlib: unable to copy file 'dist/build/libHShls-cabal-fmt-plugin-2.4.0.0-7I56G7mFmaj7IPuAfOey3q-ghc9.6.3.a'; reason: **No space left on device**

Again.
@locallycompact If you have a solution to provide a nix runner I am interested. Otherwise the Nix build system will have to be decommissioned from the CI pipeline, which would be very sad. :(

**Comment by tchoutri** [comment]
Let's try again in GHC 9.8

**Pull request closed without merging**
