### PR TITLE
[FLORA-460] Lower the default DB pool connection number

### LINKED ISSUE #460: Hang on import-index
## Environment

* Operating System: NixOS
* Toolchain (compiler + version): ghc-9.4.7
* Version or commit: #452

This has also been confirmed by @tchoutri on the development branch.

## Expected Behaviour

For everything to run to completion and successfully import an index.

## Actual Behaviour

It sets up the package and requirements tables but then just hangs indefinitely. Running it again seems to get it to finish successfully.

## Instructions for reproduction

Using `bsdtar` allow you to create a subset of the hackage index to test this, for example just with the servant package here.

```bash
$ make db-reset
$ cabal update
$ bsdtar -c -f test-index.tar --include='servant/**.cabal' @/home/$USER/.cabal/packages/hackage.haskell.org/01-index.tar
$ gzip test-index.tar
$ cabal run flora-cli -- import-index test-index.tar.gz --repository hackage
```

### PR DESCRIPTION
**Pull request by tchoutri**
fixes #460

## Proposed changes

Lower the db pool connections number to 50 in order to avoid saturating the DB server when both the application **and** an import job are running simultaneously.

### CODE REVIEW

**Comment by RaoulHC** [comment]
As a PR lgtm.

I'm not entirely sure it fixes the root issue, which is that an exception on the client side causes the process to hang with no output regarding the cause. Though maybe we should create another issue so at least if it comes up again in another form, it's documented.

**Comment by tchoutri** [comment]
@RaoulHC I think the root issue might be at the pg driver level, which is far below decks for us. :/

**Comment by RaoulHC** [comment]
> @RaoulHC I think the root issue might be at the pg driver level, which is far below decks for us. :/

Given the exceptions are caught on the server side my hunch is its in poolboy where the exceptions getting lost but I'm by no means certain.

**Comment by tchoutri** [comment]
We can perhaps ask @blackheaven directly, for poolboy. :)

**Comment by blackheaven** [comment]
`poolboy` is an in-memory queue system, jobs are executed in dedicated worker threads, that's why you cannot catch it from the main thread.

I'm not sure it's related to your PR intent, but, IIRC, when I have introduced it, I have set the number of workers to the number on PostGreSQL connections, maybe it would be worth decoupling them.

**Comment by RaoulHC** [comment]
I looked into it a bit more into it and it seems the hanging is to do with the empty logging function, though I'm not entirely certain or sure why.
I tried to debug our case by using the `simpleSerializedLogger` and was unable to reproduce it with the logging though I still could without. Changing the default log function in poolboy as follows causes it to output the error and stop, rather than silently hang, but something strange is going on.

```diff
- log = \_ -> return ()
+ log = \x -> seq x $ return ()
```

**Comment by blackheaven** [comment]
Thanks, I'll do it asap

**Comment by RaoulHC** [comment]
I've gone down a bit of a rabbit hole of concurrency and exceptions today, ended up swapping out the logging function in poolboy for using `log-base` so that I could share the same logging framework as flora and try to debug it better.

The previous suggestion seems to improve the situation but not entirely fix it. For reasons I can't quite figure out the exception can end up getting raised outside of the `tryAny` in the worker thread, changing to using the `unliftio` package is a bit better and the exception can be propagated to the main thread more often, but it still seems to slip past this and not get caught, and I'm not entirely sure how to ensure it's caught in the worker thread. Doesn't help that turning on profiling and changing optimisation seems to change the behaviour of it, seems like it's some subtle result of laziness.

**Comment by blackheaven** [comment]
I've done a [release](https://hackage.haskell.org/package/poolboy-0.2.2.0)

**Comment by tchoutri** [comment]
It is integrated in [Horizon Haskell](https://gitlab.horizon-haskell.net/package-sets/horizon-platform/-/merge_requests/48)

**Pull request merged**
